#!/usr/bin/env python
"""
This is shortcut command to run simulate.py in ns3 ./waf shell

it will call a commond line tool which let NS3 load fs dot format
configuration file and generate pcap data file
"""
from __future__ import print_function

# import settings_dot as settings
import sys
import os
ROOT =  os.path.abspath('../..')
sys.path.insert(0, ROOT)
import settings

import subprocess

exec_file = 'dotns3.py'
cmd = settings.ROOT + '/core/ns3/' + exec_file + ' ' + ' '.join(sys.argv[1:])
waf_cmd = ['export', 'PYTHONPATH=$PYTHONPATH:%s'%(ROOT), '&&']
waf_cmd += ['cd', settings.NS3_PATH, '&&', './waf', '--pyrun', '"%s"'%(cmd)]

print( '--> %s'%(' '.join(waf_cmd)) )
subprocess.check_call(' '.join(waf_cmd), shell=True)
